EXTENSION = pg_apriori_parallel         # the extensions name
DATA = pg_apriori_parallel--0.1.0.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
