EXTENSION = pg_apriori         # the extensions name
DATA = pg_apriori--0.0.2.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
